# Generated by Django 3.2.4 on 2021-06-18 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Naziv')),
            ],
            options={
                'verbose_name': 'Grupa',
                'verbose_name_plural': 'Grupe',
            },
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Naziv')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
            ],
            options={
                'verbose_name': 'Faza takmičenja',
                'verbose_name_plural': 'Faze takmičenja',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Naziv')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Opis')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/teams/', verbose_name='Sličica')),
                ('goals_scored', models.IntegerField(default=0, help_text='Koliko golova je tim postigao?', verbose_name='Postignuti golovi')),
                ('goals_received', models.IntegerField(default=0, help_text='Koliko golova je tim primio?', verbose_name='Primljeni golovi')),
                ('wins', models.IntegerField(blank=True, default=0, help_text='Koliko pobeda je tim imao?', null=True, verbose_name='Pobede')),
                ('loses', models.IntegerField(blank=True, default=0, help_text='Koliko poraza je tim imao?', null=True, verbose_name='Porazi')),
                ('draws', models.IntegerField(blank=True, default=0, help_text='Koliko puta je tim odigrao nerešen meč?', null=True, verbose_name='Remiji')),
                ('points', models.IntegerField(default=0, help_text='Koliko tim ima bodova?', verbose_name='Bodovi')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='matches.group', verbose_name='Grupa')),
            ],
            options={
                'verbose_name': 'Tim',
                'verbose_name_plural': 'Timovi',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Naslov')),
                ('overview', models.TextField(blank=True, null=True, verbose_name='Sažetak')),
                ('date', models.DateField(help_text='Kada je odigran meč?', verbose_name='Datum')),
                ('team1_goals', models.IntegerField(help_text='Koliko golova je postigao tim 1?', verbose_name='Golovi tima 1')),
                ('team2_goals', models.IntegerField(help_text='Koliko golova je postigao tim 2?', verbose_name='Golovi tima 2')),
                ('stadium', models.CharField(help_text='Na kom stadionu je igran meč?', max_length=200, verbose_name='Stadion')),
                ('spectators', models.IntegerField(help_text='Koliko je ljudi bilo na tribinama?', verbose_name='Gledaoci')),
                ('referee', models.CharField(help_text='Ko je bio glavni sudija na ovom meču?', max_length=100, verbose_name='Sudija')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='matches.match', verbose_name='Sledeći meč')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='matches.phase', verbose_name='Faza takmičenja')),
                ('previous_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='matches.match', verbose_name='Prethodni meč')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_hosted', to='matches.team', verbose_name='Tim 1')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_away', to='matches.team', verbose_name='Tim 2')),
            ],
            options={
                'verbose_name': 'Meč',
                'verbose_name_plural': 'Mečevi',
            },
        ),
    ]
