# Generated by Django 3.2.4 on 2021-07-13 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='thumbnail',
        ),
    ]
